# Generated by Django 2.1.7 on 2019-08-13 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Order'),
        ),
    ]
