# Generated by Django 2.1.7 on 2019-08-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190813_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Order'),
        ),
    ]
