# Generated by Django 2.1.7 on 2019-08-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190813_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='order',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Order'),
        ),
    ]
