# Generated by Django 2.1.7 on 2019-08-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190813_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Profile'),
        ),
    ]
